Sistema/Sistema/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.Educacion import views 
from django.contrib.auth.views import login, logout_then_login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.Educacion.urls', namespace="educacion")),
    url(r'^$',views.index,name='index'),
    #url(r'^completar/',views.completar,name='completar'),

    url(r'^accounts/login/', login, {'template_name':'iniciar.html'}, name='iniciar'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^captcha/', include('captcha.urls')),
    
]

Sistema/apps/Educacion/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from apps.Educacion.views import *

from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$',index),
	url(r'^encuesta/',encuesta,name='consultarEncuesta'),
	url(r'^tablas/',tablas,name='vertablas'),
	url(r'^reporte/', reporte),
	
	url(r'^pregunta/(?P<id_encuesta>\d+)/$',pregunta,name='consultarPregunta'),
	url(r'^preguntaDetalle/(?P<id_pregunta>[0-9]+)/$', pregunta_select, name='detalle_pregunta'),
	url(r'^(?P<pregunta_id>[0-9]+)/estadistica/$', estadistica, name='estadistica'),
	url(r'^registroIp/',registroIPa,name='registroIp'),
	url(r'^seguimiento/(?P<id_encuesta>\d+)/$',verSeguimiento,name='seguimiento'),
	url(r'^seguimientoEncuesta/',seguimientoEncuesta,name='seguimientoEnc'),
	url(r'^(?P<id_encuesta>[0-9]+)/finalizar/$', finalizar, name='finalizarA'),
	url(r'^nosotros/',nosotros),
	url(r'^graficar/(?P<pregunta_id>[0-9]+)/$',graficar,name='grafico'),
	url(r'^captchaValidar/(?P<id_encuesta>[0-9]+)/$',validar_captcha,name='validar_captcha2'),
	url(r'^seguimiento_usuario/',seguimientoEncuestaUsuario,name='ver_seguimiento_usuario'),

	



]

Sistema/templates/Registro_IP.html
{% extends "base.html" %}
{% block contenido %}
<br>
	<center><h1 id="titulosesion">Dirección IP actual</h1></center>
	<hr class="hr2">
	<h2 id="tituloIP">Su dirección IP es:</h2>
	<h1 id="dirIP">{{ip}}</h1>
{% endblock contenido %}

Sistema/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Percepcion de la calidad de educacion</title>
    {% block EstiloCSS %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'css/plugins/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    {% endblock EstiloCSS %}
    
    {% block JSGrafico %}
        
    {% endblock JSGrafico %}
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Inicio</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{user.username}}<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      
                        
                        <li>
                            <a href="/logout/"><i class="fa fa-fw fa-power-off"></i> Cerrar Sesion</a>
                        </li>
                    </ul>
                </li>
            </ul>
                {% else %}
                <li class="dropdown">
                    <a href="/accounts/login/" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Inicie Sesion<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/accounts/login/"><i class="fa fa-fw fa-user"></i> Iniciar Sesion</a>
                        </li>
                    </ul>
                </li>
            </ul>
            {% endif %}
            

            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="/encuesta"><i class="fa fa-file-text-o"></i>  Realizar Encuesta</a>
                    </li>
                    {% if user.is_authenticated == 0 %}
                        <li><a href="/seguimiento_usuario"><i class="fa fa-fw fa-bar-chart-o"></i> Ver seguimiento</a></li>
                    {% endif %}
                    
                    {% if user.is_authenticated %}
                    <li>
                    <a href="/seguimientoEncuesta"><i class="fa fa-fw fa-bar-chart-o"></i> Ver seguimiento</a>
                    </li>
                    <li>
                        <a href="/tablas"><i class="fa fa-fw fa-table"></i> Tablas de encuesta</a>
                    </li>
                    <li>
                        <a href="/admin"><i class="fa fa-fw fa-edit"></i> Editar encuesta</a>
                    </li>
                  <li>
                        <a href="/reporte"><i class="fa fa-fw fa-table"></i> Presentar Resumen</a>
                    </li>

                     
                    {% endif %}}
                    <hr>
                    <li>
                        <a href="/nosotros"><i class="fa fa-info"></i> Quienes Somos </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        {% block contenido %}
        <body background="{% static 'img/bannerpro.png' %}" width="200%"/>
       
        <div class="container">
        <br>
        <br>
        <center><img src="{% static 'img/BannerEdusy.jpg' %}" class="img-thumbnail" alt="Cinque Terre" width="430" height="436"></center>
           <br>
            <h1 id="tituloIS">Percepción de la educación<br> media en El Salvador</h1>
         <center> <a id="subtitulo" href="/encuesta/"></i>Resolver la encuesta ahora </a></center> 
           
        </div>
        <div class="container">
        <br>
        <br>
       <center><img class="fotoEdusy2" src="{% static 'img/edusy.png' %}"></center>
  <br>
    <br>
    <br>
      </br>
      </br>
    </br>
  </br>
  </div>
    {% endblock contenido %}
    {% block JS %}
    <script src="{% static 'js/jquery.js'%}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Morris Charts JavaScript -->
    {% endblock %}
    <!-- jQuery -->
    

</body>


</html>

Sistema/templates/encuesta.html
{% extends "base.html" %}
{% load staticfiles %}



{% block EstilosCSS %}
{{ block.super }}



{% endblock EstilosCSS %}
{% block contenido %}

<body  background="{% static 'img/educaciontrans.png' %}" width="200%"/>

<!--<div align="center">{{form}}</div>-->

 <br>

<center><h2 id="titulosesion">Listado de encuestas disponibles</h2></center>
 <hr class="hr2">
<form>
    
        
    <div class="container"> 
    <table class="table table-bordered">
    <thead>
      <tr>
        <th><h4>Titulo de la encuesta</h4></th>
        <th><h4>Compartir Facebook</h4></th>
        <th><h4>Compartir Twitter</h4></th>
        <th><h4>Compartir Google+</h4></th>
      </tr>
    </thead>
    <tbody>
    {%for encuesta in encuestas %}
      <tr>
        <td><a href="{% url 'educacion:validar_captcha2' encuesta.id %}" id="EnunciadoEncuestas">{{forloop.counter}}.&nbsp{{encuesta.titulo}}</a></td>
        <td><iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2F{{host}}%3A8000%2FcaptchaValidar%2F{{encuesta.id}}%2F&layout=button&size=large&mobile_iframe=true&width=98&height=28&appId" width="98" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true">
        </iframe></td>
        <td><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://127.0.0.1:8000/encuesta" data-size="large" data-dnt="true">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></td>
        <td><div>
    <script src="https://apis.google.com/js/platform.js" async defer>
    {lang: 'es-419'}
    </script>

    <div class="g-plus" data-action="share" data-height="24" data-href="http://127.0.0.1:8000/encuesta/"></div>
    </div></td>
      </tr>
    {% endfor %}
    </tbody>
    </table>                                                 
 
    </div>
     <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">

                {% if encuestas.has_previous %}
                <li><a href="?page={{ encuesta.previous_page_number }}&#encuesta">Anterior</a></li>
                {% endif %}

                {% for pg in encuestas.paginator.page_range %}
                {% if encuestas.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% else %}
                <li><a href="?page={{ pg }}&#encuesta">{{ pg }}</a></li>
                {% endif %}
                {% endfor%}
                {% if encuestas.has_next %}
                <li><a href="?page={{ encuestas.next_page_number }}&#encuesta">Siguiente</a></li>
                {% endif %}
                
            </ul>
        </div>
        <li>
      
     </li>
    </div>

  <center><a  class="btn btn-primary" href="/">Regresar a la pagina de inicio<a></center>
</form>

</form>

</body>
{% endblock contenido %}

Sistema/templates/index.html
{% extends "base.html" %}

Sistema/templates/iniciar.html
{% extends "base.html" %}
{% load staticfiles %}
{% block contenido %}
  <body  background="{% static 'img/gradiente55.png' %}" width="200%"/>
<br>
<header><h1 id="titulosesion">Sistema de encuesta de la calidad de educacion media</h1></header>
<br>
<hr>
<h4  id="Txtacceder"> Acceder</h4>
<hr>

<form class="form-horizontal" method="post" action="/admin/login/?next=/">
{% csrf_token %}
  
  <div>
 
    <div class="form-group">
    <h4  style="text-align: left" id="usuarioS">Usuario</h4>
      <input type="text" id="usr" name="username" placeholder="Ingrese su usuario">
    </div>
  </div>
  <div>
  <br>
    <div class="form-group">
    <h4 id="contraS" class="form-group">Contraseña</h4> 
      <input type="password" id="psw" name="password" placeholder="Ingrese su contraseña">
    </div>
  </div>
  
  <div> 
    <div class="form-group">

  </div>
      <button type="submit" style="background: LightSlateGray; border-color: black; margin-bottom: 0%; margin-left: 0%; margin-right: 0%;margin-top: 0%" id="btnEntrar">Ingresar</button>
     
    </div>

  </div>
  
  
  
</form>

{% endblock contenido %}

Sistema/templates/mostrar_grafico.html
{% extends "base.html" %}
{% load staticfiles %}
{% load mathfilters %}
{% block contenido %}
<body  background="{% static 'img/gradiente3.png' %}" width="200%"/>
	
	<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
	<script type="text/javascript">
		Highcharts.chart('container', {
    chart: {
        type: 'pie',
        options3d: {
            enabled: true,
            alpha: 45
        }
    },
    title: {
        text: '{{encuesta.titulo}}'
    },
    subtitle: {
        text: '{{pregunta.nombre}}'
    },
    plotOptions: {
        pie: {
            innerSize: 100,
            depth: 45
        }
    },
    series: [{
        name: 'Respuesta',
        data: [
           
            {% for respuesta in pregunta.respuesta_set.all %}
            ['{{respuesta.titulo}}', {{respuesta.frecuencia}}],
            {% endfor %}
            
        ]
    }]
});
	</script>

<div >
  <h2>Percepcion de la poblacion acerca de la calidad de educacion</h2>
  <p>La educación tiene como objetivo permitir a todas las personas  que desarrollen todas sus capacidades y talentos sin distinciones, es decir, que todas las personas evolucionen independientemente de sus características evolutivas, personales, sociales y culturales.</p>            
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Analisis</th>
        <th>Respuesta</th>
        <th>Frecuencia</th>
        <th>Porcentaje</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Menos votado</td>
        <td>{% for respuesta in pregunta.respuesta_set.all %}
            {% if minimo == respuesta.frecuencia %}
                {{respuesta.titulo}}
            {% endif %}
        {% endfor %} </td>
        <td>{{minimo}}</td>
        <td>{{minimo|mul:100|div:suma|floatformat:-2}}%</td>
      </tr>
      <tr>
        <td>Mas votado</td>
        <td>{% for respuesta in pregunta.respuesta_set.all %}
            {% if maximo == respuesta.frecuencia %}
                {{respuesta.titulo}}
            {% endif %}
        {% endfor %}</td>
        <td>{{maximo}}</td>
        <td>{{maximo|mul:100|div:suma|floatformat:-2}}%</td>
      </tr>
  
    </tbody>
  </table>
</div>
<div id="container1" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script type="text/javascript">
    Highcharts.chart('container1', {
    chart: {
        type: 'line'
    },
    title: {
        text: '{{encuesta.titulo}}'
    },
    subtitle: {
        text: '{{pregunta.nombre}}'
    },
    xAxis: {
        categories: [{% for respuesta in pregunta.respuesta_set.all %}
            '{{respuesta.titulo}}',
        {% endfor %}
        
        ]
    },
    yAxis: {
        title: {
            text: 'Tendencia (Votos)'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                enabled: true
            },
            enableMouseTracking: false
        }
    },
    series: [
    {
        name: 'Respuesta',
        data: [{% for respuesta in pregunta.respuesta_set.all %}
            {{respuesta.frecuencia}},
        {% endfor %}
        ]
    }]
});
</script>

</body>


<center><a href="{% url 'educacion:seguimiento' encuesta.id %}" class="btn btn-primary">Regresar</a></center>
{% endblock contenido %}
{% block JSGrafico %}
	<script src="{% static 'js/highcharts.js' %}"></script>
	<script src="{% static 'js/exporting.js'%}"></script>
{% endblock JSGrafico %}

Sistema/templates/pregunta_detalle.html
{% extends "base.html" %}
{% load staticfiles %}

{% block contenido %}
<body background="{% static 'img/gradiente7.jpg' %}">
<h1 class="white typed" style="color: white">{{pregunta.nombre}}</h1>
<br><br><br><br>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form class="list-group-item" action="{% url 'educacion:estadistica' pregunta.id %}" method="post">
	{% csrf_token %}
		{% for respuesta in pregunta.respuesta_set.all %}
    		<input type="radio" name="respuesta" id="respuesta{{ forloop.counter }}" value="{{ respuesta.id }}" />
    		<h4><label class="list-group-item" for="respuesta{{ forloop.counter }}">{{ respuesta.titulo }}</label></h4><br />
		{% endfor %}
		<center><input class="btn btn-primary btn-md" type="submit" value="Elija su respuesta!"></center>

	</form>
</body>
{% endblock contenido %}

Sistema/templates/preguntas.html
{% extends "base.html" %}
{% load staticfiles %}
{% block contenido %}
<body background="{% static 'img/green.jpeg' %}" width="200%"/>

    {% if bandera == 0 %}
 <h3 id="caja">&nbsp&nbsp&nbsp&nbsp&nbsp{{contador}} &nbsp  preguntas sin contestar</h3>
<br>
<br>
<br>       
    
<form align="center" action="{% url 'educacion:finalizarA' idencuesta %}" method="post">
{% csrf_token %}
	{%for pregunta in preguntas %}	
	<div id="container">
		<h4><label id="estiloPregunta"><a href="{% url 'educacion:detalle_pregunta' pregunta.id %}">{{forloop.counter}}.&nbsp{{pregunta.nombre}}</a></label></h4><br>

	{% endfor %}
    {% if preguntas.has_next == 0 %}
        {% if contador == 0 %}
        <center><input type="submit" class="btn btn-primary" value="finalizar"></center>
            {% else %}
            <h1 class="alert alert-info">Usted no ha completado la encuesta</h1>
        {% endif %}
    {% endif %}
   
   
</form>    
    </div>
	 <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">

                {% if pregunta.has_previous %}
                <li><a href="?page={{ pregunta.previous_page_number }}&#pregunta">Anterior</a></li>
                {% endif %}

                {% for pg in preguntas.paginator.page_range %}
                {% if preguntas.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% else %}
                <li><a href="?page={{ pg }}&#pregunta">{{ pg }}</a></li>
                {% endif %}
                {% endfor%}
                {% if preguntas.has_next %}
                <li><a href="?page={{ preguntas.next_page_number }}&#pregunta">Siguiente</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
    {% else %}
    <h1 class="alert alert-danger">La encuesta no puede realizarse, su dirección IP ya ha sido registrada.</h1>
    <center><a href="{% url 'educacion:consultarEncuesta' %}" class="btn btn-primary"> Regresar</a></center>
    {% endif %}
</body>
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


{% endblock contenido %}

Sistema/templates/reporte.html
{% extends "base.html" %}
{% load staticfiles %}
{% block contenido %}

  <body  background="{% static 'img/green.jpeg' %}" width="200%"/>
<br>
<header>
<h1 id="titulosesion">Resumen de datos obtenidos</h1></header>
<hr class="hr2">
<br>
    <div class="container">
  <h2>Tabla conceptual de encuesta por pregunta</h2>
  <p>Es un breve analisis de como es la tendencia de cada encuesta con sus respectivas preguntas, se basara en la percepcion de la calidad de educacion de educacion media</p>
  <table class="table">
    <thead>
      <tr>
        <th>Encuestas</th>
        <th>Cantidad de preguntas</th>
      </tr>
    </thead>
    <tbody>
    {% for contar in contar %}
        {% for encuesta in encuesta %}   
      <tr class="success">
            {% if encuesta.id == contar.encuesta_id %}
                <td>{{encuesta.titulo}}</td>
                <td>{{contar.total}}</td>
            {% endif %}
        {% endfor %} 
        {% endfor %}
        
      </tr>
    </tbody>
  </table>
</div>
     <center><div id="container" style="min-width: 310px; height: 400px; max-width: 900px; margin: 0auto"></div></center>

     <script type="text/javascript">
     Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Encuesta por pregunta'
    },
    subtitle: {
        text: ''
    },
    xAxis: {
        categories: [
        {% for contar in contar %}
        {% for encuesta in encuesta %}   
            {% if encuesta.id == contar.encuesta_id %}
                '{{encuesta.titulo}}',
            {% endif %}
        {% endfor %} 
        {% endfor %}
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'No de pregunta(s)'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} pregunta(s)</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{
        name:
        'Cantidad de preguntas',    
        data: [
        {% for contar in contar %}
        {% for encuesta in encuesta %}   
            {% if encuesta.id == contar.encuesta_id %}
                {{contar.total}},
            {% endif %}
        {% endfor %} 
        {% endfor %}
        
        ]
        
    }]
});
      
     </script>
     <br>
     <br>
    <div class="container">
 
  <div class="panel-group">
    {% for reporte in des_reporte %}
      <div class="panel panel-primary">
      <div class="panel-heading">{{reporte.encuesta.titulo}}</div>
      <div class="panel-body">{{reporte.descripcion}}</div>
    </div> <br>
    {% endfor %}
    </div><br>
    
<br>

      <center><a  class="btn btn-primary" href="/">Regresar a la pagina de inicio<a></center>
</body>
{% endblock contenido %}

{% block JSGrafico %}
	<script src="{% static 'js/highcharts.js' %}"></script>
{% endblock JSGrafico %}

</div>

Sistema/templates/seguimientoEncuesta.html
{% extends "base.html" %}
{% load staticfiles %}
{% load mathfilters %}
{% block contenido %}
  <body  background="{% static "img/fondoNaranja.png" %}" width="200%"/>
	 <form>
   <br>
 	<center><h2 id="titulosesion">Ver seguimiento de los resultados</h2></center>
  <hr class="hr2">
  
	<div class="container">
  	<p id="textoSeguimiento">A continuación se presentan los estados actuales de las encuestas citadas:</p> 
  	<table class="table ">

    	<thead>
      		<tr>
        		<th id="colornegro">Encuestas</th>
            <th>Muestra</th>
            <th>Cantidad de encuestas realizadas</th>
        		<th>Faltante</th>
      		</tr>

    	</thead>
    	{%for encuesta in encuestas %}
    		<tbody>
      			<tr>
        		<td><a id="nomcolor" href="{% url 'educacion:seguimiento' encuesta.id %}">{{encuesta.titulo}}
            &nbsp&nbsp {% if 3|sub:encuesta.realizadas == 0 %} 
            (Finalizada)
            {% endif %}</a></td>
            <td>3</td>
            <td>{{encuesta.realizadas}}</td>
            <td>
            {{3|sub:encuesta.realizadas}}
             
             
            </td></tr>
    		</tbody>
    	{% endfor %}
  	</table>
	</div>
  <br>
  <br>
	<center><a  class="btn btn-primary" href="/">Regresar a la pagina de inicio<a></center>
	</form>
  </body>
{% endblock contenido %}

Sistema/templates/ver_seguimiento.html
{% extends "base.html" %}
{% block contenido %}
{% load staticfiles %}
<body background="{% static "img/gradiente6.jpg" %}">
<center><h4>Resultados de las encuestas</h4></center>
	 <div class="progress">
  <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{cpregunta}}%">
    Preguntas
  </div>
</div>



  <div class="panel panel-primary">
      <div class="panel-heading">{{encuestas.titulo}}</div>
      <div class="panel-body">
      {% for pregunta in  encuestas.pregunta_set.all %}
        {{forloop.counter}}.&nbsp<a href="{% url 'educacion:grafico' pregunta.id %}">{{pregunta.nombre}}</a><br>
      {% endfor %}

      </div>
    </div>
    {% if user.is_authenticated %}
      <center><a class="btn btn-primary btn-small" href="/tablas">Ver tablas de encuesta</a></center><br>
    {% endif %}
	
	   {% if user.is_authenticated %}
       <center><a class="btn btn-primary btn-md" href="/seguimientoEncuesta">Regresar</a></center>
       {% else %}
       <center><a class="btn btn-primary btn-md" href="/seguimiento_usuario">Regresar</a></center>
     {% endif %}
  
</body>
{% endblock contenido%}

Sistema/templates/ver_seguimiento_usuario.html
{% extends "base.html" %}
{% load staticfiles %}
{% block contenido %}
	<body  background="{% static 'img/estadistico.png'%}" width="200%"/>
	 <form>
   <br>
 	<center><h2 id="titulosesion">Ver seguimiento de los resultados</h2></center>
  <hr>
  
	<div class="container">
  	<p id="textoSeguimiento">A continuación se presentan los estados actuales de las encuestas citadas:</p> 
  	<table class="table table-striped">

    	<thead>
      		<tr>
        		<th>Encuestas</th>
      		</tr>

    	</thead>
    	{%for encuesta in encuestas %}
    		<tbody>
      			<tr>
        		<td><a href="{% url 'educacion:seguimiento' encuesta.id %}">{{forloop.counter}}.&nbsp{{encuesta.titulo}}
            </td>
            </tr>
    		</tbody>
    	{% endfor %}
  	</table>
	</div>

	<center><a  class="btn btn-primary" href="/">Regresar a la pagina de inicio<a></center>
	</form>
  </body>
{% endblock contenido %}